# Site settings
title: Albevia Blog
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. This site is designed to present Jekyll to web designers in a clear, concise way, and provide a resource and reference for those that are new to Jekyll."
baseurl: "/blog" 
url: "http://albevia.github.io/blog" 
tagline: Software Building Blocks for Disruptive Age 

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
gems: [jekyll-paginate]
paginate_path: '/blog/page:num/'
permalink: /blog/:title
