# Site settings
title: Albevia Blog
email: feedback@albevia.com
description: "Sharing concrete ideas related to software development for this disruptive age."
baseurl: "/blog" 
url: "http://albevia.github.io/blog" 
tagline: Software Building Blocks for Disruptive Age 

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
gems: [jekyll-paginate]
paginate_path: '/blog/page:num/'
permalink: /blog/:title
